# numpy模組

## ★統計分析套件安裝

## ★1.多維陣列建立及查詢屬性
    np.array() 建立時在小括號內填上中括號, 再將陣列數值放在中括號內, 彼此以逗號隔開

In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])   #np.array() 建立陣列

print(arr)          # 輸出陣列本身
print(arr.ndim)     # 陣列的維度數 (dimension) (這裡是 2維陣列，所以是 2)
print(arr.shape)    # 陣列的形狀 (各維度大小)   (這裡是 2X3 陣列，所以是 (2,3))
print(arr.size)     # 陣列的元素總數 (這裡是 6)
print(arr.dtype)    # 陣列中元素的資料型態 (這裡是 int64 或 int32，依系統而定)
print(arr.itemsize) # 單一元素佔用的位元組數 (bytes)，例如 (int64 = 8 bytes, int32 = 4 bytes)
print(arr.nbytes)   # 整個陣列佔用的記憶體大小

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
4
24


## ★建立其他陣列

In [36]:
import numpy as np
#建立內容全是 0 的多維陣列
arr1 = np.zeros((2,3))
print(arr1)  

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
#建立內容全是 1 的多維陣列
arr2=np.ones((2,3))
print(arr2)  

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
#建立未初始化的陣列
arr3=np.empty((2,3))
print(arr3)  

[[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
#使用linspace(start, end, num) 建立等分區間的數列,
#start:起始值; end:結束值; num:多少個等距點, 預設是0
arr4=np.linspace(0,1,5)
print(arr4)  

[0.   0.25 0.5  0.75 1.  ]


In [40]:
#使用arange(start, stop, step)建立等差數列
#start:起始值; stop: 結束值但產生數列不包含此值; step:陣列間距, 預設是1
arr5=np.arange(0,10,2)
print(arr5) 

[0 2 4 6 8]


In [41]:
#使用diag()建立建立對角矩陣，其他位置為 0
arr6=np.diag([1,2,3])
print(arr6) 

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [42]:
#使用eye()建立nxn單位陣列 (Identity Matrix)
arr7=np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#使用tile()重複拼貼陣列
arr8=np.tile([1,2], (2,3))
print(arr8)

[[1 2 1 2 1 2]
 [1 2 1 2 1 2]]


## ★2.陣列四則運算與函數運算

In [31]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# 陣列四則運算 (element-wise, 元素對應運算)
print(A + B)   # [5 7 9]
print(A - B)   # [-3 -3 -3]
print(A * B)   # [ 4 10 18]
print(A / B)   # [0.25 0.4  0.5]

# 向量內積 (dot product)/矩陣乘法 np.dot 或 @
print('向量內積： \n', np.dot(A, B))  # 1*4 + 2*5+ 3*6 = 32

# 陣列數學函數運算
print('平均值： \n',np.mean(A))  # 平均值 -> (1+2+3)/3 = 2.0
print('標準差： \n',np.std(A))   # 標準差 -> 約 0.816

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
向量內積： 
 32
平均值： 
 2.0
標準差： 
 0.816496580927726


## ★3.線性代數

In [32]:
import numpy as np
m = np.array([[1, 2], [3, 4]])

print('矩陣乘法：\n', m @ m)  
print('轉置矩陣：\n', m.T)                
print('行列式：\n', np.linalg.det(m))      
print('反矩陣：\n', np.linalg.inv(m))       
eigvals, eigvecs = np.linalg.eig(m)
print('特徵值：\n', eigvals)   
print('特徵向量：\n', eigvecs)

矩陣乘法：
 [[ 7 10]
 [15 22]]
轉置矩陣：
 [[1 3]
 [2 4]]
行列式：
 -2.0000000000000004
反矩陣：
 [[-2.   1. ]
 [ 1.5 -0.5]]
特徵值：
 [-0.37228132  5.37228132]
特徵向量：
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## ★4.隨機亂數產生

In [33]:
r = np.random.rand(3, 3)   # 3x3 隨機矩陣
n = np.random.normal(0, 1, 10)  # 平均0, 標準差1 的10個樣本
u = np.random.uniform (-1, 1, 10)  # -1 至 1 均勻分配的10個樣本
print('隨機矩陣 \n', r)
print('標準常態分配樣本 \n',n)
print('均勻分配樣本 \n',u)

隨機矩陣 
 [[0.46534991 0.49987162 0.59632669]
 [0.23876894 0.16209341 0.34226331]
 [0.85165897 0.86827534 0.28320392]]
標準常態分配樣本 
 [ 0.61709639  0.37036353  0.20919729  0.44182134  0.02430431  1.26513901
  0.71949843 -0.55107817 -0.82910346  0.88928545]
均勻分配樣本 
 [-0.15966768 -0.02169976 -0.08431232 -0.77173596 -0.958664    0.86259838
  0.51836923  0.142588   -0.80626615 -0.31034627]


## ★5.陣列操作：索引、切片、廣播與重塑

In [50]:
import numpy as np
x1=[1,2,3]
x2=[4,5,6]
x=np.array([x1, x2])          # list 轉換成 2x3 NumPy 陣列

# 索引 (indexing)，直接用「座標」取出特定元素，從 0 開始編號。
print('x[0, 0]=', x[0, 0])    # 取第1列第1欄 → 1
print('x[1][2]=', x[1][2])    # 取第2列第3欄 → 6

# 切片 (slicing)
print('x[1,:2]=', x[1,:2])    # 第1列前2個 → [1 2]
print('x[:,1]=', x[:, 1])     # 所有列的第2欄 → [2 5]
print('x[1, 1:]=',x[1, 1:])   # 第2列從第2欄到最後 → [5 6]

# 廣播 (Broadcasting) 自動對齊運算：矩陣 + 向量、向量 + 常數。
print('x+10= \n', x + 10)                 # 每個元素都自動加上 10

x[0, 0]= 1
x[1][2]= 6
x[1,:2]= [4 5]
x[:,1]= [2 5]
x[1, 1:]= [5 6]
x+10= 
 [[11 12 13]
 [14 15 16]]


## ★ 5.陣列操作：陣列結合插入刪除

In [44]:
#concatenate()陣列結合
y1=np.array([1,2,3])
y2=np.array([4,5])
y3=np.concatenate((y1,y2)) #注意二個小括號
print(y3)

[1 2 3 4 5]


In [45]:
#insert()在陣列索引插入元素
x=np.array([1,2,3])
z=np.insert(x, 2,9)
print(z)

[1 2 9 3]


In [47]:
#delete()刪除指定索引在陣列元素
x=np.array([1,2,3,4,5])
z=np.delete(x, 1)
print(z)

[1 3 4 5]


## ★5.陣列操作：更改陣列外形

In [51]:
#更改陣列外形
import numpy as np
x=np.arange(15)
print(f'原陣列 x={x}')
y=np.reshape(x,(3,5))
print(f'原陣列 y=\n {y}') #\n代表跳行

原陣列 x=[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
原陣列 y=
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [52]:
# 多維轉一維, 回傳檢視(VIEW)
import numpy as np
y1=[ 0,  1,  2,  3,  4]
y2=[ 5,  6,  7,  8,  9]
y3= [10, 11, 12, 13, 14]
y=np.array([y1, y2, y3])
z=y.ravel()
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [53]:
# 多維轉一維, 回傳拷貝(COPY)
import numpy as np
y1=[ 0,  1,  2,  3,  4]
y2=[ 5,  6,  7,  8,  9]
y3= [10, 11, 12, 13, 14]
y=np.array([y1, y2, y3])
z=y.flatten()
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## ★5.陣列操作：陣列分割與合併

In [56]:
#陣列水平分割
import numpy as np 
x=np.arange(16).reshape(4,4)
print(f'x= \n {x}')    #\n代表跳行

x1,x2=np.hsplit(x,2)
print(f'x1= \n {x1}')  #\n代表跳行
print(f'x2= \n {x2}')

x= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
x1= 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
x2= 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [58]:
#陣列垂直分割
import numpy as np 
x=np.arange(16).reshape(4,4)
print(f'x= \n {x}')    #\n代表跳行

x1,x2=np.vsplit(x,2)
print(f'x1=\n {x1}')
print(f'x2= \n {x2}')

x= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
x1=
 [[0 1 2 3]
 [4 5 6 7]]
x2= 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [59]:
#陣列垂直合併
x1=np.arange(4).reshape(2,2)
x2=np.arange(4,8).reshape(2,2)
x=np.vstack((x1,x2))
print(f'x1= \n {x1}')
print(f'x2= \n {x2}')
print(f'合併陣列= \n {x}')

x1= 
 [[0 1]
 [2 3]]
x2= 
 [[4 5]
 [6 7]]
合併陣列= 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [60]:
#陣列水平合併
x1=np.arange(4).reshape(2,2)
x2=np.arange(4,8).reshape(2,2)
x=np.hstack((x1,x2))
print(f'x1= \n {x1}')
print(f'x2= \n {x2}')
print(f'合併陣列= \n {x}')

x1= 
 [[0 1]
 [2 3]]
x2= 
 [[4 5]
 [6 7]]
合併陣列= 
 [[0 1 4 5]
 [2 3 6 7]]
